[snowflake]
user='user'
password='password'
account='org-account'
role='sysadmin'
database='db'
schema='schema'
warehouse='warehouse'

[cognito]
cognito_domain=''
client_id=''
client_secret=''
app_uri=''
region = ''
pool_id = ''